name: docs

on:
  push:
    branches:
      - '2.*'
      - 'development'
      - '!2.0b'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Checkout phoebe2-docs master
      uses: actions/checkout@v2
      with:
        repository: phoebe-project/phoebe2-docs
        path: phoebe2-docs-master

    - name: Build docs
      env: `echo ${{ github.ref }} | cut -d "/" -f 3`
      run: |
        mkdir -p phoebe2-docs-master/${{ env.branch }}/tutorials
        mkdir -p phoebe2-docs-master/${{ env.branch }}/examples
        jupyter nbconvert --to python tutorials/*ipynb --output-dir=phoebe2-docs-master/${{ env.branch }}/tutorials
        jupyter nbconvert --to python examples/*ipynb --output-dir=phoebe2-docs-master/${{ env.branch }}/examples
        cp tutorials/*ipynb phoebe2-docs-master/${{ env.branch }}/tutorials/
        cp examples/*ipynb phoebe2-docs-master/${{ env.branch }}/examples/
        cd phoebe2-docs-master
        git config --global user.email "gh-actions"
        git config --global user.name "gh-actions"
        git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
        git add ${{ env.branch }}/tutorials/*
        git add ${{ env.branch }}/examples/*
        git commit -m "building ${{ env.branch }} docs"
        git push -q -f https://kecnry:${{ secrets.GH_API_KEY }}@github.com/phoebe-project/phoebe2-docs master
