name: docs

on:
  push:
    branches:
      - '2.*'
      - 'development'
      - '!2.0b'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Build docs
      run: |
        git clone --depth 1 git://github.com/phoebe-project/phoebe2-docs.git ../phoebe2-docs-master
        mkdir -p ../phoebe2-docs-master/${ GIT_BRANCH_NAME }/tutorials
        mkdir -p ../phoebe2-docs-master/${ GIT_BRANCH_NAME }/examples
        jupyter nbconvert --to python tutorials/*ipynb --output-dir=../phoebe2-docs-master/${ GIT_BRANCH_NAME }/tutorials
        jupyter nbconvert --to python examples/*ipynb --output-dir=../phoebe2-docs-master/${ GIT_BRANCH_NAME }/examples
        cp tutorials/*ipynb ../phoebe2-docs-master/${ GIT_BRANCH_NAME }/tutorials/
        cp examples/*ipynb ../phoebe2-docs-master/${ GIT_BRANCH_NAME }/examples/
        cd ../phoebe2-docs-master
        git config --global user.email "gh-actions"
        git config --global user.name "gh-actions"
        git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
        git add ${ GIT_BRANCH_NAME }/tutorials/*
        git add ${ GIT_BRANCH_NAME }/examples/*
        git commit -m 'building ${ GIT_BRANCH_NAME } docs'
        git push -q -f https://kecnry:${{ secrets.GH_API_KEY }}@github.com/phoebe-project/phoebe2-docs master
